# Generated by Django 4.2.3 on 2023-08-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(default=None, max_length=100)),
                ('singer', models.CharField(max_length=200)),
                ('album_title', models.CharField(max_length=500)),
                ('album_picture', models.ImageField(default=False, upload_to='uploads')),
            ],
        ),
    ]
