# Generated by Django 4.2.3 on 2023-08-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song',
            field=models.FileField(default='', upload_to='media/uploads'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_picture',
            field=models.ImageField(default=False, upload_to='media/uploads'),
        ),
    ]
