# Generated by Django 4.2.3 on 2023-08-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_song_alter_song_album_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('rearrange_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='album_picture',
            field=models.ImageField(default=False, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(default='', upload_to='uploads'),
        ),
    ]
