# Generated by Django 4.2.3 on 2023-08-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_viewer_alter_song_album_picture_alter_song_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='viewer_name',
        ),
        migrations.AddField(
            model_name='viewer',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='viewer',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='viewer',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='viewer',
            name='user_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='rearrange_password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
