# Generated by Django 4.2.3 on 2023-08-08 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0004_remove_viewer_viewer_name_viewer_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch_later',
            fields=[
                ('watch_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
